#  ____                       _____
# |  _ \                     |  __ \
# | |_) |  ___   __ _  _ __  | |__) |__ _  ___  ___
# |  _ <  / _ \ / _` || '_ \ |  ___// _` |/ __|/ __|
# | |_) ||  __/| (_| || | | || |   | (_| |\__ \\__ \
# |____/  \___| \__,_||_| |_||_|    \__,_||___/|___/

# General Settings
QuestsPerPlayer: 5

# Quest Difficulties To Be Set For Individual Quests
Difficulties:
  SUPER_EASY:
    base_units: 16
    max_unit_multiplier: 32
    xp_per_unit: 0.1
  VERY_EASY:
    base_units: 8
    max_unit_multiplier: 16
    xp_per_unit: 0.5
  EASY:
    base_units: 4
    max_unit_multiplier: 8
    xp_per_unit: 1
  NORMAL:
    base_units: 4
    max_unit_multiplier: 8
    xp_per_unit: 5
  HARD:
    base_units: 2
    max_unit_multiplier: 8
    xp_per_unit: 15
  VERY_HARD:
    base_units: 2
    max_unit_multiplier: 4
    xp_per_unit: 50
  SUPER_HARD:
    base_units: 1
    max_unit_multiplier: 4
    xp_per_unit: 100

# All Possible Mining Quests And Its Respective Difficulty
MiningQuestDifficulties:
  STONE:
    difficulty: SUPER_EASY
  DEEPSLATE:
    difficulty: SUPER_EASY
  ANDESITE:
    difficulty: VERY_EASY
  DIORITE:
    difficulty: VERY_EASY
  GRANITE:
    difficulty: VERY_EASY
  TUFF:
    difficulty: VERY_EASY
  GRAVEL:
    difficulty: VERY_EASY
  CLAY:
    difficulty: EASY
  COAL_ORE:
    difficulty: EASY
  DEEPSLATE_COAL_ORE:
    difficulty: EASY
  COPPER_ORE:
    difficulty: NORMAL
  DEEPSLATE_COPPER_ORE:
    difficulty: NORMAL
  IRON_ORE:
    difficulty: NORMAL
  DEEPSLATE_IRON_ORE:
    difficulty: NORMAL
  NETHER_GOLD_ORE:
    difficulty: NORMAL
  NETHER_QUARTZ_ORE:
    difficulty: NORMAL
  DRIPSTONE_BLOCK:
    difficulty: NORMAL
  SCULK:
    difficulty: NORMAL
  SCULK_SENSOR:
    difficulty: HARD
  MOSSY_COBBLESTONE:
    difficulty: HARD
  LAPIS_ORE:
    difficulty: HARD
  DEEPSLATE_LAPIS_ORE:
    difficulty: HARD
  REDSTONE_ORE:
    difficulty: HARD
  DEEPSLATE_REDSTONE_ORE:
    difficulty: HARD
  GOLD_ORE:
    difficulty: HARD
  DEEPSLATE_GOLD_ORE:
    difficulty: HARD
  EMERALD_ORE:
    difficulty: VERY_HARD
  DEEPSLATE_EMERALD_ORE:
    difficulty: VERY_HARD
  DIAMOND_ORE:
    difficulty: VERY_HARD
  DEEPSLATE_DIAMOND_ORE:
    difficulty: VERY_HARD
  ANCIENT_DEBRIS:
    difficulty: SUPER_HARD

# All Possible Lumber Quests And Its Respective Difficulty
LumberQuestDifficulties:
  OAK_LOG:
    difficulty: VERY_EASY
  SPRUCE_LOG:
    difficulty: VERY_EASY
  BIRCH_LOG:
    difficulty: VERY_EASY
  JUNGLE_LOG:
    difficulty: VERY_EASY
  ACACIA_LOG:
    difficulty: VERY_EASY
  DARK_OAK_LOG:
    difficulty: VERY_EASY
  MANGROVE_ROOTS:
    difficulty: EASY
  CRIMSON_STEM:
    difficulty: EASY
  WARPED_STEM:
    difficulty: EASY

KillingQuestDifficulties:
  BLAZE:
    difficulty: HARD
  CAVE_SPIDER:
    difficulty: NORMAL
  CHICKEN:
    difficulty: EASY
  COW:
    difficulty: EASY
  CREEPER:
    difficulty: NORMAL
  DROWNED:
    difficulty: NORMAL
  ELDER_GUARDIAN:
    difficulty: SUPER_HARD
  ENDER_DRAGON:
    difficulty: SUPER_HARD
  ENDERMAN:
    difficulty: HARD
  ENDERMITE:
    difficulty: HARD
  EVOKER:
    difficulty: VERY_HARD
  GHAST:
    difficulty: HARD
  GLOW_SQUID:
    difficulty: NORMAL
  GOAT:
    difficulty: NORMAL
  GUARDIAN:
    difficulty: HARD
  HOGLIN:
    difficulty: HARD
  HUSK:
    difficulty: HARD
  ILLUSIONER:
    difficulty: VERY_HARD
  MAGMA_CUBE:
    difficulty: HARD
  MUSHROOM_COW:
    difficulty: HARD
  PHANTOM:
    difficulty: HARD
  PIG:
    difficulty: EASY
  PIGLIN:
    difficulty: NORMAL
  PIGLIN_BRUTE:
    difficulty: VERY_HARD
  PILLAGER:
    difficulty: HARD
  PUFFERFISH:
    difficulty: NORMAL
  RABBIT:
    difficulty: EASY
  RAVAGER:
    difficulty: VERY_HARD
  SALMON:
    difficulty: NORMAL
  SHEEP:
    difficulty: EASY
  SHULKER:
    difficulty: HARD
  SILVERFISH:
    difficulty: HARD
  SKELETON:
    difficulty: NORMAL
  SLIME:
    difficulty: NORMAL
  SPIDER:
    difficulty: NORMAL
  SQUID:
    difficulty: EASY
  STRAY:
    difficulty: HARD
  TROPICAL_FISH:
    difficulty: NORMAL
  VEX:
    difficulty: VERY_HARD
  VINDICATOR:
    difficulty: VERY_HARD
  WARDEN:
    difficulty: SUPER_HARD
  WITCH:
    difficulty: HARD
  WITHER:
    difficulty: SUPER_HARD
  WITHER_SKELETON:
    difficulty: VERY_HARD
  ZOGLIN:
    difficulty: HARD
  ZOMBIE:
    difficulty: NORMAL
  ZOMBIFIED_PIGLIN:
    difficulty: HARD

ExplorationQuestDifficulties:
  ANCIENT_CITY:
    structures:
      - ANCIENT_CITY
    difficulty: VERY_HARD
  BASTION_REMNANT:
    structures:
      - BASTION_REMNANT
    difficulty: VERY_HARD
  BURIED_TREASURE:
    structures:
      - BURIED_TREASURE
    difficulty: NORMAL
  DESERT_PYRAMID:
    structures:
      - DESERT_PYRAMID
    difficulty: HARD
  END_CITY:
    structures:
      - END_CITY
    difficulty: VERY_HARD
  NETHER_FORTRESS:
    structures:
      - FORTRESS
    difficulty: HARD
  IGLOO:
    structures:
      - IGLOO
    difficulty: HARD
  JUNGLE_PYRAMID:
    structures:
      - JUNGLE_PYRAMID
    difficulty: HARD
  MANSION:
    structures:
      - MANSION
    difficulty: SUPER_HARD
  MINESHAFT:
    structures:
      - MINESHAFT
      - MINESHAFT_MESA
    difficulty: HARD
  OCEAN_RUIN:
    structures:
      - OCEAN_RUIN_COLD
      - OCEAN_RUIN_WARM
    difficulty: NORMAL
  PILLAGER_OUTPOST:
    structures:
      - PILLAGER_OUTPOST
    difficulty: NORMAL
  RUINED_PORTAL:
    structures:
      - RUINED_PORTAL
      - RUINED_PORTAL_DESERT
      - RUINED_PORTAL_JUNGLE
      - RUINED_PORTAL_MOUNTAIN
      - RUINED_PORTAL_NETHER
      - RUINED_PORTAL_OCEAN
      - RUINED_PORTAL_SWAMP
    difficulty: NORMAL
  SHIPWRECK:
    structures:
      - SHIPWRECK
      - SHIPWRECK_BEACHED
    difficulty: NORMAL
  VILLAGE:
    structures:
      - VILLAGE_DESERT
      - VILLAGE_PLAINS
      - VILLAGE_SAVANNA
      - VILLAGE_SNOWY
      - VILLAGE_TAIGA
    difficulty: HARD

# Beanpass Rewards
# TYPES: MONEY, SET_HOME, SKIN
Season: 1
SeasonLevels:
  1:
    XP: 0 #amount of xp needed from the previous level
    Reward:
  2:
    XP: 25
    Reward:
      Free:
        Type: MONEY
        Amount: 10
  3:
    XP: 30
    Reward:
      Free:
        Type: MONEY
        Amount: 15
      Paid:
        Type: SKIN
        Item: carved_pumpkin
        Skin: witch_hat
  4:
    XP: 40
    Reward:
      Free:
        Type: MONEY
        Amount: 15
  5:
    XP: 50
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1
  6:
    XP: 60
    Reward:
      Free:
        Type: MONEY
        Amount: 20
      Paid:
        Type: SKIN
        Item: wooden_sword
        Skin: wooden_club
  7:
    XP: 75
    Reward:
      Free:
        Type: MONEY
        Amount: 20
  8:
    XP: 90
    Reward:
      Free:
        Type: MONEY
        Amount: 20
  9:
    XP: 105
    Reward:
      Free:
        Type: MONEY
        Amount: 20
  10:
    XP: 120
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1