#  ____                       _____
# |  _ \                     |  __ \
# | |_) |  ___   __ _  _ __  | |__) |__ _  ___  ___
# |  _ <  / _ \ / _` || '_ \ |  ___// _` |/ __|/ __|
# | |_) ||  __/| (_| || | | || |   | (_| |\__ \\__ \
# |____/  \___| \__,_||_| |_||_|    \__,_||___/|___/

# General Settings

# Quest Difficulties To Be Set For Individual Quests
Difficulties:
  SUPER_EASY:
    base_units: 8
    max_unit_multiplier: 24
    xp_per_unit: 0.0521
  VERY_EASY:
    base_units: 8
    max_unit_multiplier: 16
    xp_per_unit: 0.196
  EASY:
    base_units: 6
    max_unit_multiplier: 12
    xp_per_unit: 0.56
  NORMAL:
    base_units: 4
    max_unit_multiplier: 8
    xp_per_unit: 1.6
  HARD:
    base_units: 2
    max_unit_multiplier: 8
    xp_per_unit: 5
  VERY_HARD:
    base_units: 2
    max_unit_multiplier: 4
    xp_per_unit: 13
  SUPER_HARD:
    base_units: 1
    max_unit_multiplier: 1
    xp_per_unit: 150

CommanderQuests:
  BLAZE:
    difficulty: HARD
  CAVE_SPIDER:
    difficulty: NORMAL
  CREEPER:
    difficulty: NORMAL
  DROWNED:
    difficulty: NORMAL
  ELDER_GUARDIAN:
    difficulty: SUPER_HARD
  ENDER_DRAGON:
    difficulty: SUPER_HARD
  ENDERMAN:
    difficulty: HARD
  ENDERMITE:
    difficulty: HARD
  EVOKER:
    difficulty: VERY_HARD
  GHAST:
    difficulty: HARD
  GUARDIAN:
    difficulty: HARD
  HOGLIN:
    difficulty: HARD
  HUSK:
    difficulty: HARD
  MAGMA_CUBE:
    difficulty: HARD
  PHANTOM:
    difficulty: HARD
  PIGLIN:
    difficulty: NORMAL
  PIGLIN_BRUTE:
    difficulty: VERY_HARD
  PILLAGER:
    difficulty: HARD
  RAVAGER:
    difficulty: VERY_HARD
  SHULKER:
    difficulty: HARD
  SILVERFISH:
    difficulty: HARD
  SKELETON:
    difficulty: NORMAL
  SLIME:
    difficulty: NORMAL
  SPIDER:
    difficulty: NORMAL
  STRAY:
    difficulty: HARD
  VEX:
    difficulty: VERY_HARD
  VINDICATOR:
    difficulty: VERY_HARD
  WARDEN:
    difficulty: SUPER_HARD
  WITCH:
    difficulty: HARD
  WITHER:
    difficulty: SUPER_HARD
  WITHER_SKELETON:
    difficulty: VERY_HARD
  ZOGLIN:
    difficulty: HARD
  ZOMBIE:
    difficulty: NORMAL
  ZOMBIFIED_PIGLIN:
    difficulty: HARD

# All Possible Mining Quests And Its Respective Difficulty
MinerQuests:
  COAL_ORE:
    difficulty: EASY
  COPPER_ORE:
    difficulty: NORMAL
  IRON_ORE:
    difficulty: NORMAL
  NETHER_QUARTZ_ORE:
    difficulty: NORMAL
  LAPIS_ORE:
    difficulty: HARD
  REDSTONE_ORE:
    difficulty: HARD
  GOLD_ORE: #NETHER_GOLD_ORE, DEEPSLATE_GOLD_ORE
    difficulty: HARD
  EMERALD_ORE:
    difficulty: VERY_HARD
  DIAMOND_ORE:
    difficulty: VERY_HARD
  ANCIENT_DEBRIS:
    difficulty: SUPER_HARD

BuilderQuests:
  STONE:
    difficulty: SUPER_EASY
  SAND:
    difficulty: SUPER_EASY
  DIRT:
    difficulty: SUPER_EASY
  DEEPSLATE:
    difficulty: SUPER_EASY
  ANDESITE:
    difficulty: VERY_EASY
  DIORITE:
    difficulty: VERY_EASY
  GRANITE:
    difficulty: VERY_EASY
  TUFF:
    difficulty: VERY_EASY
  GRAVEL:
    difficulty: VERY_EASY
  CLAY:
    difficulty: EASY
  DRIPSTONE_BLOCK:
    difficulty: NORMAL
  MOSSY_COBBLESTONE:
    difficulty: HARD

FisherQuests:
  COD:
    difficulty: EASY
  SALMON:
    difficulty: NORMAL
  PUFFERFISH:
    difficulty: VERY_HARD
  TROPICAL_FISH:
    difficulty: SUPER_HARD

WitchQuests:
  FIRE_RESISTANCE:
    difficulty: NORMAL
  INSTANT_DAMAGE:
    difficulty: NORMAL
  INVISIBILITY:
    difficulty: NORMAL
  NIGHT_VISION:
    difficulty: NORMAL
  POISON:
    difficulty: NORMAL
  SLOW_FALLING:
    difficulty: HARD
  SLOWNESS:
    difficulty: NORMAL
  WEAKNESS:
    difficulty: NORMAL
  WATER_BREATHING:
    difficulty: NORMAL

BartenderQuests:
  POISON:
    difficulty: NORMAL
  STRENGTH:
    difficulty: NORMAL
  INSTANT_HEAL:
    difficulty: NORMAL
  REGEN:
    difficulty: NORMAL
  NIGHT_VISION:
    difficulty: NORMAL
  FIRE_RESISTANCE:
    difficulty: NORMAL

# All Possible Lumber Quests And Its Respective Difficulty
LumberjackQuests:
  OAK_LOG:
    difficulty: VERY_EASY
  SPRUCE_LOG:
    difficulty: VERY_EASY
  BIRCH_LOG:
    difficulty: VERY_EASY
  JUNGLE_LOG:
    difficulty: VERY_EASY
  ACACIA_LOG:
    difficulty: VERY_EASY
  DARK_OAK_LOG:
    difficulty: VERY_EASY
  MANGROVE_ROOTS:
    difficulty: EASY
  CRIMSON_STEM:
    difficulty: EASY
  WARPED_STEM:
    difficulty: EASY

ButcherQuests:
  CHICKEN:
    difficulty: EASY
  COD:
    difficulty: NORMAL
  COW:
    difficulty: EASY
  HOGLIN:
    difficulty: HARD
  MUSHROOM_COW:
    difficulty: HARD
  PIG:
    difficulty: EASY
  POLAR_BEAR:
    difficulty: HARD
  RABBIT:
    difficulty: EASY
  SALMON:
    difficulty: NORMAL
  SHEEP:
    difficulty: EASY
  TROPICAL_FISH:
    difficulty: NORMAL

ExplorationQuestDifficulties:
  ANCIENT_CITY:
    structures:
      - ANCIENT_CITY
    difficulty: VERY_HARD
  BASTION_REMNANT:
    structures:
      - BASTION_REMNANT
    difficulty: VERY_HARD
  BURIED_TREASURE:
    structures:
      - BURIED_TREASURE
    difficulty: NORMAL
  DESERT_PYRAMID:
    structures:
      - DESERT_PYRAMID
    difficulty: HARD
  END_CITY:
    structures:
      - END_CITY
    difficulty: VERY_HARD
  NETHER_FORTRESS:
    structures:
      - FORTRESS
    difficulty: HARD
  IGLOO:
    structures:
      - IGLOO
    difficulty: HARD
  JUNGLE_PYRAMID:
    structures:
      - JUNGLE_PYRAMID
    difficulty: HARD
  MANSION:
    structures:
      - MANSION
    difficulty: SUPER_HARD
  MINESHAFT:
    structures:
      - MINESHAFT
      - MINESHAFT_MESA
    difficulty: HARD
  OCEAN_RUIN:
    structures:
      - OCEAN_RUIN_COLD
      - OCEAN_RUIN_WARM
    difficulty: NORMAL
  PILLAGER_OUTPOST:
    structures:
      - PILLAGER_OUTPOST
    difficulty: NORMAL
  RUINED_PORTAL:
    structures:
      - RUINED_PORTAL
      - RUINED_PORTAL_DESERT
      - RUINED_PORTAL_JUNGLE
      - RUINED_PORTAL_MOUNTAIN
      - RUINED_PORTAL_NETHER
      - RUINED_PORTAL_OCEAN
      - RUINED_PORTAL_SWAMP
    difficulty: NORMAL
  SHIPWRECK:
    structures:
      - SHIPWRECK
      - SHIPWRECK_BEACHED
    difficulty: NORMAL
  VILLAGE:
    structures:
      - VILLAGE_DESERT
      - VILLAGE_PLAINS
      - VILLAGE_SAVANNA
      - VILLAGE_SNOWY
      - VILLAGE_TAIGA
    difficulty: HARD

# Beanpass Rewards
# TYPES: MONEY, SET_HOME, SKIN
Season: 1
SeasonLevels:
  1:
    XP: 0 #amount of xp needed from the previous level
    Reward:
  2:
    XP: 25
    Reward:
      Free:
        Type: MONEY
        Amount: 10
  3:
    XP: 30
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1
      Paid:
        Type: SKIN
        Skin: witch_hat
  4:
    XP: 40
    Reward:
      Free:
        Type: MONEY
        Amount: 15
  5:
    XP: 50
    Reward:
      Free:
        Type: MONEY
        Amount: 20
  6:
    XP: 60
    Reward:
      Free:
        Type: MONEY
        Amount: 25
  7:
    XP: 75
    Reward:
      Free:
        Type: MONEY
        Amount: 30
  8:
    XP: 90
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1
      Paid:
        Type: SKIN
        Skin: top_hat
  9:
    XP: 105
    Reward:
      Free:
        Type: MONEY
        Amount: 35
  10:
    XP: 120
    Reward:
      Free:
        Type: MONEY
        Amount: 40
  11:
    XP: 140
    Reward:
      Free:
        Type: MONEY
        Amount: 45
  12:
    XP: 160
    Reward:
      Free:
        Type: MONEY
        Amount: 50
  13:
    XP: 180
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1
      Paid:
        Type: SKIN
        Skin: santa_hat
  14:
    XP: 200
    Reward:
      Free:
        Type: MONEY
        Amount: 55
  15:
    XP: 225
    Reward:
      Free:
        Type: MONEY
        Amount: 60
  16:
    XP: 250
    Reward:
      Free:
        Type: MONEY
        Amount: 65
  17:
    XP: 275
    Reward:
      Free:
        Type: MONEY
        Amount: 70
  18:
    XP: 300
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1
      Paid:
        Type: SKIN
        Skin: hard_hat
  19:
    XP: 350
    Reward:
      Free:
        Type: MONEY
        Amount: 85
  20:
    XP: 400
    Reward:
      Free:
        Type: MONEY
        Amount: 90
  21:
    XP: 450
    Reward:
      Free:
        Type: MONEY
        Amount: 100
  22:
    XP: 500
    Reward:
      Free:
        Type: MONEY
        Amount: 120
  23:
    XP: 600
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
      Paid:
        Type: MOUNT
        Mount: lamborghini_jalpa
  24:
    XP: 700
    Reward:
      Free:
        Type: MONEY
        Amount: 140
  25:
    XP: 800
    Reward:
      Free:
        Type: MONEY
        Amount: 175

Skins:
  witch_hat:
    Material: CARVED_PUMPKIN
    ID: 116
  top_hat:
    Material: CARVED_PUMPKIN
    ID: 10009
  santa_hat:
    Material: CARVED_PUMPKIN
    ID: 10010
  hard_hat:
    Material: CARVED_PUMPKIN
    ID: 10011

Mounts:
  lamborghini_jalpa:
    Entity: HORSE
    ID: 10010