#  ____                       _____
# |  _ \                     |  __ \
# | |_) |  ___   __ _  _ __  | |__) |__ _  ___  ___
# |  _ <  / _ \ / _` || '_ \ |  ___// _` |/ __|/ __|
# | |_) ||  __/| (_| || | | || |   | (_| |\__ \\__ \
# |____/  \___| \__,_||_| |_||_|    \__,_||___/|___/

# General Settings
Season: 1
QuestsPerNPCPerDay: 6