name: BeanPass
version: '${project.version}'
main: me.karltroid.beanpass.BeanPass
api-version: 1.19

depend: [PlaceholderAPI, ActionBarAPI]

commands:
  beanpass:
    description: Open the BeanPass GUI
    usage: /beanpass
    permission: beanpass.user
    aliases: [ bp ]
  beanpass-addxp:
    description: Modify a player's BeanPass season XP
    usage: /beanpass addxp <player> <amount>
    permission: beanpass.owner
  beanpass-bedrock:
    description: Toggle whether the GUI thinks the player is bedrock for testing bedrock GUI
    usage: /beanpass bedrock <player>
    permission: beanpass.owner
  quests:
    description: View your active quests to complete
    usage: /quests
    permission: beanpass.user
    aliases: [ quest ]
  rewards:
    description: View and select your rewards earned from BeanPass
    usage: /rewards
    permission: beanpass.user
    aliases: [ reward ]
  mounts:
    description: View and select your unlocked mounts
    usage: /mounts
    permission: beanpass.user
    aliases: [ mount ]
  hats:
    description: View and select your unlocked hats
    usage: /hats
    permission: beanpass.user
    aliases: [ hat ]
  tools:
    description: View and select your unlocked tool skins
    usage: /tools
    permission: beanpass.user
    aliases: [ tool ]
  sethome:
    description: Set a home that you can teleport to with /home "<home nickname>" later
    usage: /sethome
    permission: beanpass.user
    aliases: [ esethome, createhome, ecreatehome ]
    executor: me.karltroid.beanpass.command.SetHome
  givequest:
    description: Give a player a quest from a NPC
    usage: /givequest <npc> <player>
    permission: beanpass.owner
    aliases: [ gq, gquest ]
  requestteleport:
    description: Ask player if they want to teleport
    usage: /requestteleport <player> <world> <x> <y> <z> <yes_msg> | <no_msg>
    permission: beanpass.owner