name: BeanPass
version: '${project.version}'
main: me.karltroid.beanpass.BeanPass
api-version: 1.19

commands:
  beanpass:
    description: Open the BeanPass GUI
    usage: /beanpass
    permission: beanpass.user
    aliases: [ bp ]
    executor: me.karltroid.beanpass.command.OpenBeanPassGUI
  beanpass-addxp:
    description: Add XP to a player's BeanPass
    usage: /beanpass addxp <player> <xp>
    permission: beanpass.admin
    executor: me.karltroid.beanpass.command.AddXP
  quests:
    description: View the player's active quests
    usage: /quests
    permission: beanpass.user
    aliases: [ quest ]
    executor: me.karltroid.beanpass.command.ViewQuests