name: BeanPass
version: '${project.version}'
main: me.karltroid.beanpass.BeanPass
api-version: 1.19

commands:
  beanpass:
    description: Open the BeanPass GUI
    usage: /beanpass
    permission: beanpass.user
    aliases: [ bp ]
  beanpass-addxp:
    description: Modify a player's BeanPass season XP
    usage: /beanpass addxp <player> <amount>
    permission: beanpass.admin
  quests:
    description: View your active quests to complete
    usage: /quests
    permission: beanpass.user
    aliases: [ quest ]
  rewards:
    description: View and select your rewards earned from BeanPass
    usage: /rewards
    permission: beanpass.user
    aliases: [ reward ]
  mounts:
    description: View and select your unlocked mounts
    usage: /mounts
    permission: beanpass.user
    aliases: [ mount ]
  hats:
    description: View and select your unlocked hats
    usage: /hats
    permission: beanpass.user
    aliases: [ hat ]
  tools:
    description: View and select your unlocked tool skins
    usage: /tools
    permission: beanpass.user
    aliases: [ tool ]
  yesno:
    description: testing for yes no display
    usage: /yesno
    permission: beanpass.admin
    aliases: [ yn ]
  sethome:
    description: Set a home that you can teleport to with /home "<home nickname>" later
    usage: /sethome
    permission: beanpass.user
    aliases: [ esethome, createhome, ecreatehome ]
    executor: me.karltroid.beanpass.command.ViewQuests
  givequest:
    description: Give a player a quest from a NPC
    usage: /givequest <npc> <player>
    permission: beanpass.admin
    aliases: [ gq, gquest ]