# Beanpass Rewards
# TYPES: MONEY, SET_HOME, SKIN
SeasonLevels:
  '1':
    XP: 0 # amount of xp needed from the previous level
  '2':
    XP: 30
    Reward:
      Free:
        Type: MONEY
        Amount: 15
      Paid:
        Type: SKIN
        Skin: top_hat
  '3':
    XP: 39
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1
  '4':
    XP: 48
    Reward:
      Free:
        Type: MONEY
        Amount: 25
      Paid:
        Type: SKIN
        Skin: witch_hat
  '5':
    XP: 56
    Reward:
      Free:
        Type: MONEY
        Amount: 30
  '6':
    XP: 74
    Reward:
      Free:
        Type: MONEY
        Amount: 40
  '7':
    XP: 90
    Reward:
      Free:
        Type: MONEY
        Amount: 50
      Paid:
        Type: SKIN
        Skin: hard_hat
  '8':
    XP: 97
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1
  '9':
    XP: 104
    Reward:
      Free:
        Type: MONEY
        Amount: 60
      Paid:
        Type: SKIN
        Skin: santa_hat
  '10':
    XP: 128
    Reward:
      Free:
        Type: MONEY
        Amount: 75
  '11':
    XP: 150
    Reward:
      Free:
        Type: MONEY
        Amount: 90
  '12':
    XP: 172
    Reward:
      Free:
        Type: MONEY
        Amount: 105
      Paid:
        Type: SKIN
        Skin: beansprout_hat
  '13':
    XP: 180
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1
  '14':
    XP: 188
    Reward:
      Free:
        Type: MONEY
        Amount: 120
      Paid:
        Type: MOUNT
        Mount: canoe
  '15':
    XP: 215
    Reward:
      Free:
        Type: MONEY
        Amount: 140

  '16':
    XP: 241
    Reward:
      Free:
        Type: MONEY
        Amount: 160
  '17':
    XP: 266
    Reward:
      Free:
        Type: MONEY
        Amount: 180
      Paid:
        Type: SKIN
        Skin: fishbowl_hat
  '18':
    XP: 275
    Reward:
      Free:
        Type: SET_HOME
        Amount: 1
  '19':
    XP: 284
    Reward:
      Free:
        Type: MONEY
        Amount: 200
      Paid:
        Type: SKIN
        Skin: ram_horns_hat
  '20':
    XP: 313
    Reward:
      Free:
        Type: MONEY
        Amount: 225
  '21':
    XP: 341
    Reward:
      Free:
        Type: MONEY
        Amount: 250
  '22':
    XP: 367
    Reward:
      Free:
        Type: MONEY
        Amount: 275
      Paid:
        Type: SKIN
        Skin: bunny_ears_hat
  '23':
    XP: 373
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '24':
    XP: 385
    Reward:
      Free:
        Type: MONEY
        Amount: 300
      Paid:
        Type: SKIN
        Skin: captain_hat
  '25':
    XP: 408
    Reward:
      Free:
        Type: MONEY
        Amount: 325
  '26':
    XP: 431
    Reward:
      Free:
        Type: MONEY
        Amount: 350
  '27':
    XP: 453
    Reward:
      Free:
        Type: MONEY
        Amount: 375
      Paid:
        Type: MOUNT
        Mount: lamborghini_jalpa
  '28':
    XP: 461
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '29':
    XP: 464
    Reward:
      Free:
        Type: MONEY
        Amount: 400
      Paid:
        Type: SKIN
        Skin: cat_ears_hat
  '30':
    XP: 483
    Reward:
      Free:
        Type: MONEY
        Amount: 425
  '31':
    XP: 501
    Reward:
      Free:
        Type: MONEY
        Amount: 450
  '32':
    XP: 545
    Reward:
      Free:
        Type: MONEY
        Amount: 500
      Paid:
        Type: SKIN
        Skin: candle_hat
  '33':
    XP: 561
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '34':
    XP: 576
    Reward:
      Free:
        Type: MONEY
        Amount: 550
      Paid:
        Type: SKIN
        Skin: bone_hat
  '35':
    XP: 616
    Reward:
      Free:
        Type: MONEY
        Amount: 600
  '36':
    XP: 654
    Reward:
      Free:
        Type: MONEY
        Amount: 650
  '37':
    XP: 690
    Reward:
      Free:
        Type: MONEY
        Amount: 700
      Paid:
        Type: SKIN
        Skin: party_hat
  '38':
    XP: 701
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '39':
    XP: 710
    Reward:
      Free:
        Type: MONEY
        Amount: 750
      Paid:
        Type: SKIN
        Skin: space_helmet_hat
  '40':
    XP: 743
    Reward:
      Free:
        Type: MONEY
        Amount: 800
  '41':
    XP: 773
    Reward:
      Free:
        Type: MONEY
        Amount: 850
  '42':
    XP: 802
    Reward:
      Free:
        Type: MONEY
        Amount: 900
      Paid:
        Type: SKIN
        Skin: unicorn_hat
  '43':
    XP: 808
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '44':
    XP: 813
    Reward:
      Free:
        Type: MONEY
        Amount: 950
      Paid:
        Type: SKIN
        Skin: smul_birthday_hat
  '45':
    XP: 839
    Reward:
      Free:
        Type: MONEY
        Amount: 1000
  '46':
    XP: 904
    Reward:
      Free:
        Type: MONEY
        Amount: 1100
  '47':
    XP: 967
    Reward:
      Free:
        Type: MONEY
        Amount: 1200
      Paid:
        Type: SKIN
        Skin: battle_axe
  '48':
    XP: 987
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '49':
    XP: 1006
    Reward:
      Free:
        Type: MONEY
        Amount: 1300
      Paid:
        Type: MOUNT
        Mount: demon_train
  '50':
    XP: 1062
    Reward:
      Free:
        Type: MONEY
        Amount: 1400
  '51':
    XP: 1115
    Reward:
      Free:
        Type: MONEY
        Amount: 1500
  '52':
    XP: 1165
    Reward:
      Free:
        Type: MONEY
        Amount: 1600
      Paid:
        Type: SKIN
        Skin: frown_mask
  '53':
    XP: 1178
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '54':
    XP: 1189
    Reward:
      Free:
        Type: MONEY
        Amount: 1700
      Paid:
        Type: SKIN
        Skin: smile_mask
  '55':
    XP: 1234
    Reward:
      Free:
        Type: MONEY
        Amount: 1800
  '56':
    XP: 1276
    Reward:
      Free:
        Type: MONEY
        Amount: 1900
  '57':
    XP: 1317
    Reward:
      Free:
        Type: MONEY
        Amount: 2000
      Paid:
        Type: SKIN
        Skin: headphones
  '58':
    XP: 1355
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '59':
    XP: 1391
    Reward:
      Free:
        Type: MONEY
        Amount: 2200
      Paid:
        Type: SKIN
        Skin: pig_ears
  '60':
    XP: 1487
    Reward:
      Free:
        Type: MONEY
        Amount: 2400
  '61':
    XP: 1579
    Reward:
      Free:
        Type: MONEY
        Amount: 2600
  '62':
    XP: 1666
    Reward:
      Free:
        Type: MONEY
        Amount: 2800
      Paid:
        Type: SKIN
        Skin: racoon_tail_cap
  '63':
    XP: 1691
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '64':
    XP: 1715
    Reward:
      Free:
        Type: MONEY
        Amount: 3000
      Paid:
        Type: SKIN
        Skin: bat
  '65':
    XP: 1792
    Reward:
      Free:
        Type: MONEY
        Amount: 3200
  '66':
    XP: 1866
    Reward:
      Free:
        Type: MONEY
        Amount: 3400
  '67':
    XP: 1937
    Reward:
      Free:
        Type: MONEY
        Amount: 3600
      Paid:
        Type: SKIN
        Skin: pitchfork
  '68':
    XP: 1951
    Reward:
      Free:
        Type: SET_HOME
        Amount: 2
  '69':
    XP: 1963
    Reward:
      Free:
        Type: MONEY
        Amount: 3800
  '70':
    XP: 2025
    Reward:
      Free:
        Type: MONEY
        Amount: 4000