name: BeanPass
version: '1.0'
main: me.karltroid.beanpass.BeanPass
api-version: 1.19

commands:
  beanpass:
    description: Open the BeanPass GUI
    usage: /beanpass
    permission: beanpass.user
    aliases: [ bp ]
    executor: me.karltroid.beanpass.command.BeanPassCommand
  beanpass-addxp:
    description: Modify a player's BeanPass season XP
    usage: /beanpass addxp <player> <amount>
    permission: beanpass.admin
    executor: me.karltroid.beanpass.command.BeanPassCommand
  quests:
    description: View the player's active quests
    usage: /quests
    permission: beanpass.user
    aliases: [ quest ]
    executor: me.karltroid.beanpass.command.ViewQuests
  sethome:
    description: Set a home that you can teleport to with /home "<home nickname>" later
    usage: /sethome
    permission: beanpass.user
    aliases: [ esethome, createhome, ecreatehome ]
    executor: me.karltroid.beanpass.command.ViewQuests
  mounttest:
    description: Testing mounts
    usage: /mounttest
    permission: beanpass.admin
    aliases: [ mount ]
    executor: me.karltroid.beanpass.command.MountTest