name: BeanPass
version: '1.0'
main: me.karltroid.beanpass.BeanPass
api-version: 1.19

commands:
  beanpass:
    description: Open the BeanPass GUI
    usage: /beanpass
    permission: beanpass.user
    aliases: [ bp ]
  beanpass-addxp:
    description: Modify a player's BeanPass season XP
    usage: /beanpass addxp <player> <amount>
    permission: beanpass.admin
  quests:
    description: View the player's active quests
    usage: /quests
    permission: beanpass.user
    aliases: [ quest ]
    executor: me.karltroid.beanpass.command.ViewQuests